reviewApp/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/event'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/products'

  resources :products, :shallow => true 
    


  resources :users
  resources :sessions
  resources :reviews
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reviewApp/app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews
	 validates_uniqueness_of :product_id
	has_attached_file :image
	validates_attachment :image, content_type: { content_type:/\Aimage\/.*\z/ }, size: { less_than: 1.megabyte }


end

reviewApp/app/models/profile.rb
class Profile < ApplicationRecord
	has_attached_file :image
	validates_attachment :image, content_type: { content_type:/\Aimage\/.*\z/ }, size: { less_than: 1.megabyte }
    has_secure_password
    validates_uniqueness_of :email
    has_many :reviews
end

reviewApp/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
end

reviewApp/app/models/user.rb
class User < ApplicationRecord
		has_attached_file :image
	validates_attachment :image, content_type: { content_type:/\Aimage\/.*\z/ }, size: { less_than: 1.megabyte }
    has_secure_password
    validates_uniqueness_of :email
    has_many :reviews
end

reviewApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	private 
	def current_user
		@current_user||=User.find(session[:user_id]) if session[:user_id]
	end
	
	helper_method :current_user
	
	def authorize 
		redirect_to new_session_path, alert: 'Please Log in or Sign up' if current_user.nil?
	end

end

reviewApp/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authorize, :only => [:create]
	def index
	@products=Product.all
	end

	def new
	end 

	def show
		@product=Product.find(params[:id])
    end

	def create
		#render plain: params[:product].inspect
		@product=Product.new(product_params)
		if @product.save
		redirect_to products_path, notice:
		"you've added a product"
	else
		redirect_to products_path, alert:
		"you need to be signed in to create a product"
	end
  end 

	private
	def product_params
		params.require(:product).permit(:productName, :brand, :cost, :category, :date, :description, :image)
	end

end

reviewApp/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def index
      @profiles=Profile.all
	end

	def new
		@profile = Profile.new
	end

		def show
		@profile=Profile.find(params[:id])
	end

	def create 
		@profile=Profile.new(user_params)
		if @profile.save
			redirect_to static_pages_home, notice:
			"welcome #{@profile.userid}! to reviewApp"
		else 
			render 'new'
		end
	end

		private
	def user_params
		params.require(:profile).permit(:userid, :email, :password, :name, :dob, :address, :city, :country, :image, :password_confirmation)
	end

end

end

reviewApp/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authorize, :only => [:create]
  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end
 
  def edit
  end

  def create
     @review = Review.new(review_params)
     #@review.userid = current_user.id

    if @review.save
      redirect_to @product
    else 
      render 'new'
    end
  end

  def update
  end

  def destroy
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end
    def review_params
      params.require(:review).permit(:author, :rating, :reviewtext, :reviewdate, :userid, :image_file_path, :product_id)
    end
end

reviewApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def index
		redirect_to root_path, notice:
		"welcome #{@user.userid}! to reviewApp"
	end

	def new
	end

	def create
		user=User.find_by_userid(params[:userid])
		if user && user.authenticate(params[:password])
			session[:user_id]=user.id
			redirect_to root_path
		else
			render 'new', alert:
			"invalid username and/or password"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice:
		"you have successfully logged out"
	end
		
end

reviewApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def products
  end
end

reviewApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
      @users=User.all
	end

	def new
		@user = User.new
	end

		def show
		@user=User.find(params[:id])
	end

	def create 
		@user=User.new(user_params)
		if @user.save
			redirect_to products_path, notice:
			"welcome #{@user.userid}! to reviewApp"
		else 
			render 'new'
		end
	end

		private
	def user_params
		params.require(:user).permit(:userid, :email, :password, :name, :dob, :address, :city, :country, :image, :password_confirmation)
	end

end

reviewApp/app/helpers/products_helper.rb
module ProductsHelper
end

reviewApp/app/helpers/reviews_helper.rb
module ReviewsHelper
end

reviewApp/app/views/products/index.html.erb
<div class="container">
<h2> Products Available </h2>
<table border="1" class="table">
<tr>
<th>Product id</th>
<th>Product Name</th>
<th>Product Brand</th>
<th>Product Price</th>
<th>Product Category</th>
<th>Product Release Date</th>
<th>Product Description</th>
</tr>

<% @products.each do |product| %>

<tr>
<td> <%= product.id %> </td>
<td> <%= product.brand %> </td>
<td> <%= product.cost %> </td>
<td> <%= product.category %> </td>
<td> <%= product.date %> </td>
<td> <%= product.description %> </td>
<td> <%= link_to 'product page', product_path(product) %> </td>
</tr>
<% end %>
</table>
</div>

reviewApp/app/views/products/new.html.erb
<div class="container">

<h1> Add New Product </h1>
<%= form_for :product, url: products_path do |f| %>

<div class="form-group">
<%= f.label :productName %>
<%= f.text_field :productName %>
</div>

<div class="form-group">
<%= f.label :brand %>
<%= f.text_field :brand %>
</div>

<div class="form-group">
<%= f.label :cost %>
<%= f.number_field :cost %>
</div>

<div class="form-group">
<%= f.label :category %>
<%= f.text_field :category %>
</div>

<div class="form-group">
<%= f.label :date %>
<%= f.date_field :date %>
</div>

<div class="form-group">
<%= f.label :description %>
<%= f.text_area :description %>
</div>

<div class="form-group">
<%= f.label :image %>
<%= f.file_field :image %>
</div>

<div class="form-group">
<%= f.submit %>
</div>
<% end %>
</div>

reviewApp/app/views/products/show.html.erb
<div class="container">
<h3> Product Details <h3>
<p>Product id: <%= @product.id %> </p>
<p>Product Name: <%= @product.productName %> </p>
<p>Product Brand: <%= @product.brand %> </p>
<p>Product Price: <%= @product.cost %> </p>
<p>Product Category: <%= @product.category %> </p>
<p>Product Date Added: <%= @product.date %> </p>
<p>Product Description: <%= @product.description %> </p>
<%= image_tag (@product.image.url) if @product.image.exists? %>
</div>
<%= link_to "write a review", new_product_review_path(@product) %>

reviewApp/app/views/profiles/new.html.erb
<div class="container">
	<h2>Create Acount</h2>
	<%= form_for @profile do |f| %>
	<div class="field" style="100%">
		<% if @profile.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@profile.errors.count, "error") %>
				prohibited this from being saved:
			</h2>
			<p>
				<ul>
					<%= @profile.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>						
					</li>
				</ul>
				<% end %>
			</p>
			<% if alert %>
			<%= alert %>
			<% end %>
		</div>
		<% end %>
		<%= f.text_field :userid, placeholder: 'Enter a Username', class: 'form-control' %>
		<%= f.email_field :email, placeholder: 'Enter your Email', class: 'form-control' %>
		<%= f.password_field :password, placeholder: 'Create A Password', class: 'form-control' %>
		<%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control' %>
			<%= f.text_field :name, placeholder: 'Enter your name', class: 'form-control' %>
		<%= f.date_field :dob, placeholder: 'Enter your date of birth', class: 'form-control' %>
		<%= f.text_field :address, placeholder: 'enter your address', class: 'form-control' %>
			<%= f.text_field :city, placeholder: 'Enter your city', class: 'form-control' %>
		<%= f.text_field :country, placeholder: 'Enter your country', class: 'form-control' %>
		<%= f.file_field :image, placeholder: 'add a profile picture', class: 'form-control' %>



		<%= f.submit 'Create Account' %>
		<% end %>
		</div>
		</div>

reviewApp/app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :reviewtext %>
    <%= form.text_area :reviewtext %>
  </div>

  <div class="field">
    <%= form.label :reviewdate %>
    <%= form.date_select :reviewdate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

reviewApp/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

reviewApp/app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Rating</th>
      <th>Reviewtext</th>
      <th>Reviewdate</th>
      <th>Userid</th>
      <th>Image file path</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.author %></td>
        <td><%= review.rating %></td>
        <td><%= review.reviewtext %></td>
        <td><%= review.reviewdate %></td>
        <td><%= review.userid %></td>
        <td><%= review.image_file_path %></td>
        <td><%= review.product_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

reviewApp/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

reviewApp/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @review.author %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Reviewtext:</strong>
  <%= @review.reviewtext %>
</p>

<p>
  <strong>Reviewdate:</strong>
  <%= @review.reviewdate %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @review.userid %>
</p>

<p>
  <strong>Image file path:</strong>
  <%= @review.image_file_path %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

reviewApp/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

reviewApp/app/views/static_pages/event.html.erb
<h1>StaticPages#event</h1>
<p>Find me in app/views/static_pages/event.html.erb</p>

reviewApp/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

reviewApp/app/views/static_pages/products.html.erb
<h1>StaticPages#products</h1>
<p>Find me in app/views/static_pages/products.html.erb</p>

reviewApp/app/views/users/new.html.erb
<div class="container">
	<h2>Create Acoount</h2>
	<%= form_for @user do |f| %>
	<div class="field" style="100%">
		<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@user.errors.count, "error") %>
				prohibited this from being saved:
			</h2>
			<p>
				<ul>
					<%= @user.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>						
					</li>
				</ul>
				<% end %>
			</p>
			<% if alert %>
			<%= alert %>
			<% end %>
		</div>
		<% end %>
		<%= f.text_field :userid, placeholder: 'Enter a Username', class: 'form-control' %>
		<%= f.email_field :email, placeholder: 'Enter your Email', class: 'form-control' %>
		<%= f.password_field :password, placeholder: 'Create A Password', class: 'form-control' %>
		<%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control' %>
			<%= f.text_field :name, placeholder: 'Enter your name', class: 'form-control' %>
		<%= f.date_field :dob, placeholder: 'Enter your date of birth', class: 'form-control' %>
		<%= f.text_field :address, placeholder: 'enter your address', class: 'form-control' %>
			<%= f.text_field :city, placeholder: 'Enter your city', class: 'form-control' %>
		<%= f.text_field :country, placeholder: 'Enter your country', class: 'form-control' %>
		<%= f.file_field :image, placeholder: 'add a profile picture', class: 'form-control' %>



		<%= f.submit 'Create Account' %>
		<% end %>
		</div>
		</div>