eventApp/config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :users
  resources :profiles
  resources :contacts
   get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/events'
  resources :sessions
  root 'static_pages#home'
  resources :home, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

eventApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eventApp/app/models/contact.rb
class Contact < ApplicationRecord
end

eventApp/app/models/event.rb
class Event < ApplicationRecord
end

eventApp/app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

eventApp/app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :events
  has_secure_password
  validates_uniqueness_of :email
end

eventApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
		protect_from_forgery with: :exception

	private 
	def current_user
		@current_user||=User.find(session[ :user_id]) if session[ :user_id]
	end
	
	helper_method :current_user
	
	def authorize 
		redirect_to new_session_path, alert: 'Please Log in or Sign up' if current_user.nil?
	end

end

eventApp/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]


  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit


  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Contact was successfully submitted.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:fname, :email, :address, :subject, :reason)
    end
end

eventApp/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:ename, :etype, :location, :city, :tickets, :edate, :etime, :description, :user_id)
    end
end

eventApp/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def new
		@profile = current_user.build_profile
	end

	def show
		@profile = Profile.where(:user_id => params[:id]).first
	end

	def create
		  @profile = current_user.build_profile(profile_params)
		if @profile.save
		  redirect_to root_path
	      else
		  render 'new'
	    end
	end

	def update
		@profile = Profile.where(:user_id => params[:id]).first
		if @profile.update(profile_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def edit
		@profile = Profile.where(:user_id => params[:id]).first
	end

	private
	def profile_params
		params.require(:profile).permit(:fname, :dob, :address, :city, :country, :user_id, :image)
end

end

eventApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def index
		redirect_to root_path, notice:
		"welcome #{@user.userid}! to eventApp"
	end

	def new
	end

	def create
		user=User.find_by_userid(params[:userid])
		if user && user.authenticate(params[:password])
			session[:user_id]=user.id
			redirect_to root_path
		else
			render 'new', alert:
			"invalid username and/or password"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice:
		"you have successfully logged out"
	end
		
end

eventApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def events
  end
end

eventApp/app/controllers/user_controller.rb
class UserController < ApplicationController

		def index
      @users=User.all
	end

	def new
		@user = User.new
	end

	def create 
		@user = User.new(user_params)
		if @user.save
			redirect_to new_profile_path, notice:
			"welcome #{@user.userid}! to reviewApp please login with your newly created credentials"
		else 
			render 'new'
		end
	end
    
    		private
	def user_params
		params.require(:user).permit(:userid, :email, :password, :registered, :password_confirmation)
	end


end

eventApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

		def index
      @users=User.all
	end

	def new
		@user = User.new
	end

	def create 
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to new_profile_path, notice:
			"welcome #{@user.userid}! to reviewApp please login with your newly created credentials"
		else 
			render 'new'
		end
	end
    
    		private
	def user_params
		params.require(:user).permit(:userid, :email, :password, :registered, :password_confirmation)
	end


end

eventApp/app/helpers/application_helper.rb
module ApplicationHelper
end

eventApp/app/helpers/contacts_helper.rb
module ContactsHelper
end

eventApp/app/helpers/events_helper.rb
module EventsHelper
end

eventApp/app/helpers/profiles_helper.rb
module ProfilesHelper
end

eventApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

eventApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

eventApp/app/helpers/user_helper.rb
module UserHelper
end

eventApp/app/helpers/users_helper.rb
module UsersHelper
end

eventApp/app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

eventApp/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

eventApp/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Email</th>
      <th>Address</th>
      <th>Subject</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.fname %></td>
        <td><%= contact.email %></td>
        <td><%= contact.address %></td>
        <td><%= contact.subject %></td>
        <td><%= contact.reason %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

eventApp/app/views/contacts/new.html.erb
<div class="container">
	<h2>Create Account</h2>
	<%= form_for @contact do |f| %>
	<div class="field" style="100%">
		<% if @contact.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@contact.errors.count, "error") %>
				prohibited this from being saved:
			</h2>
			<p>
				<ul>
					<%= @contact.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>						
					</li>
				</ul>
				<% end %>
			</p>
			<% if alert %>
			<%= alert %>
			<% end %>
		</div>
		<% end %>
		<%= f.text_field :fname, placeholder: 'Enter your name', class: 'form-control' %>
		<%= f.email_field :email, placeholder: 'Enter your Email', class: 'form-control' %>
		<%= f.text_field :address, placeholder: 'Enter your Address', class: 'form-control' %>
		<%= f.text_field :subject, placeholder: 'Subject of Enquery', class: 'form-control' %>
			<%= f.text_area :reason, placeholder: 'Enquery', class: 'form-control' %>


		<%= f.submit 'Submit Enquery' %>
		<% end %>
		</div>
		</div>

eventApp/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @contact.fname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @contact.reason %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

eventApp/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ename %>
    <%= form.text_field :ename %>
  </div>

  <div class="field">
    <%= form.label :etype %>
    <%= form.text_field :etype %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :tickets %>
    <%= form.text_field :tickets %>
  </div>

  <div class="field">
    <%= form.label :edate %>
    <%= form.date_select :edate %>
  </div>

  <div class="field">
    <%= form.label :etime %>
    <%= form.time_select :etime %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

eventApp/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

eventApp/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event type</th>
      <th>Location</th>
      <th>City</th>
      <th>Tickets</th>
      <th>Event date</th>
      <th>Event time</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.ename %></td>
        <td><%= event.etype %></td>
        <td><%= event.location %></td>
        <td><%= event.city %></td>
        <td><%= event.tickets %></td>
        <td><%= event.edate %></td>
        <td><%= event.etime %></td>
        <td><%= event.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

eventApp/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

eventApp/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @event.ename %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @event.etype %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>Tickets:</strong>
  <%= @event.tickets %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.edate %>
</p>

<p>
  <strong>Event time:</strong>
  <%= @event.etime %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Back', events_path %>

eventApp/app/views/profiles/edit.html.erb
<div class="container">
<h1>Edit Profile</h1>
 <%= form_for @profile, html: {multipart: true}, url: profile_path do |f| %>
    <div class="form-group">
  <%= f.label "Full Name:" %>
  <%= f.text_field :fname, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.hidden_field :user_id, :value => current_user.id  %>
 </div>
 <div class="form-group">
  <%= f.label "Date of Birth:" %>
  <%= f.date_field :dob, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "Address:" %>
  <%= f.text_field :address, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "City:" %>
  <%= f.text_field :city, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "Country:" %>
  <%= f.text_field :country, class:'form-control' %>
 </div>

 <div class="form-group">
  <%= f.label "Profile Image" %>
  <%= f.file_field :image %>
 </div>

 <div class="form-group">
  <%= f.submit "Submit", class: 'btn btn-primary' %>
 </div>

 <div class="form-group">
  <%= link_to "Cancel", profiles_path%>
 </div>

 <% end %>
</div>

eventApp/app/views/profiles/new.html.erb
<div class="container">
<h1>Create Profile</h1>
 <%= form_for :profile, html: { multipart: true}, url: profiles_path do |f| %>
   <div class="form-group">
  <%= f.hidden_field :user_id, :value => current_user.id  %>
 </div>
  <div class="form-group">
  <%= f.label "Full Name:" %>
  <%= f.text_field :fname, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "Date of Birth:" %>
  <%= f.date_field :dob, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "Address:" %>
  <%= f.text_field :address, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "City:" %>
  <%= f.text_field :city, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "Country:" %>
  <%= f.text_field :country, class:'form-control' %>
 </div>
 <div class="form-group">
  <%= f.label "Profile Image" %>
  <%= f.file_field :image %>
 </div>


 <div class="form-group">
  <%= f.submit "Submit", class: 'btn btn-primary' %>
 </div>

 <div class="form-group">
  <%= link_to "Cancel", profiles_path%>
 </div>

 <% end %>
</div>

eventApp/app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
<div class="card col-md-12" style="align: center">
    <div class="col-md-12 col-md-offset-6 mt-2">
<h3><strong><%= @profile.fname %>'s Profile</strong></h3>
<p><%= image_tag @profile.image.url,  size:'100x50' %></p> 
<p><strong>Full Name: </strong>     <br/><%= @profile.fname %></p>
<p><strong>Date of Birth: </strong> <br/>  <%= @profile.dob %></p>
<p><strong>Address:</strong>   <br/> <%= @profile.address %></p>
<p><strong>City: </strong><br/> <%= @profile.city %></p>
<p><strong>Country: </strong> <br/><%= @profile.country %></p>
<p><%= link_to 'Edit Profile', edit_profile_path(current_user.id) %></p>
<p><%= link_to 'Home', root_path %></p>
</div>
</div></div>

eventApp/app/views/static_pages/about.html.erb
<div class="container">
	<h1 class="jumbotron-heading">About Us Page</h1>
	<div class="container">
		<div class="row">
			<div class="col">
				<p>Lorem ipsum dolor sit amet, est ipsum fugit ut. Cu lorem iudicabit usu, eam eu similique voluptatibus signiferumque. Ea magna homero molestiae est, wisi veri mel ei, ad magna erant vel. Oblique torquatos rationibus ea eum, ei molestiae maiestatis percipitur eum. Ad velit constituam sed. Ut alia meis utinam per, cu civibus dignissim pro.</p>
			</div>
			<div class="col">
				<p>Lorem ipsum dolor sit amet, est ipsum fugit ut. Cu lorem iudicabit usu, eam eu similique voluptatibus signiferumque. Ea magna homero molestiae est, wisi veri mel ei, ad magna erant vel. Oblique torquatos rationibus ea eum, ei molestiae maiestatis percipitur eum. Ad velit constituam sed. Ut alia meis utinam per, cu civibus dignissim pro.</p>
			</div>
		</div>
	</div>

eventApp/app/views/static_pages/contact.html.erb
<h1 id="page_title">Contact Form</h1>

<div class="skinny_wrapper wrapper_padding">

	<label>Name</label><br>
	<input type="text">

	<br>

	<label>Email</label><br>
	<input type="text">

	<br>

	<label>Message</label><br>
	<textarea></textarea>

	<br>

	<input type="submit" value="send message" class="button">
</div>

eventApp/app/views/static_pages/events.html.erb
<h1>StaticPages#events</h1>
<p>Find me in app/views/static_pages/events.html.erb</p>

eventApp/app/views/static_pages/home.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Home Page</h1>
	<div class="container">
		<div class="row">
			<div class="col">
				<p>Lorem ipsum dolor sit amet, est ipsum fugit ut. Cu lorem iudicabit usu, eam eu similique voluptatibus signiferumque. Ea magna homero molestiae est, wisi veri mel ei, ad magna erant vel. Oblique torquatos rationibus ea eum, ei molestiae maiestatis percipitur eum. Ad velit constituam sed. Ut alia meis utinam per, cu civibus dignissim pro.</p>
			</div>
			<div class="col">
				<p>Lorem ipsum dolor sit amet, est ipsum fugit ut. Cu lorem iudicabit usu, eam eu similique voluptatibus signiferumque. Ea magna homero molestiae est, wisi veri mel ei, ad magna erant vel. Oblique torquatos rationibus ea eum, ei molestiae maiestatis percipitur eum. Ad velit constituam sed. Ut alia meis utinam per, cu civibus dignissim pro.</p>
			</div>
		</div>
	</div>

eventApp/app/views/user/new.html.erb
<div class="container">
	<h2>Create Account</h2>
	<%= form_for @user do |f| %>
	<div class="field" style="100%">
		<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@user.errors.count, "error") %>
				prohibited this from being saved:
			</h2>
			<p>
				<ul>
					<%= @user.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>						
					</li>
				</ul>
				<% end %>
			</p>
			<% if alert %>
			<%= alert %>
			<% end %>
		</div>
		<% end %>
		<%= f.text_field :userid, placeholder: 'Enter a Username', class: 'form-control' %>
		<%= f.email_field :email, placeholder: 'Enter your Email', class: 'form-control' %>
		<%= f.password_field :password, placeholder: 'Create A Password', class: 'form-control' %>
		<%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control' %>
		<%= f.date_field :registered, placeholder: 'Todays Date', class: 'form-control' %>
		<%= f.submit 'Create Account' %>
		<% end %>
		</div>
		</div>